// Copyright (c) The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0xbc,0x14,0xb6,0x4e,0x20,0x8d,
};
static const uint8_t chainparams_seed_signet[] = {
    0x01,0x04,0xbc,0x14,0xb6,0x4e,0x95,0x7d,
};
static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0xbc,0x14,0xb6,0x4e,0x47,0x9d,
};
static const uint8_t chainparams_seed_testnet4[] = {
    0x01,0x04,0xbc,0x14,0xb6,0x4e,0xbc,0xad,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
