// Copyright (c) 2023-present The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <chainparams.h>
#include <common/args.h>
#include <common/init.h>
#include <logging.h>
#include <tinyformat.h>
#include <util/fs.h>
#include <util/translation.h>

#include <algorithm>
#include <exception>
#include <fstream>
#include <optional>

namespace common {
std::optional<ConfigError> InitConfig(ArgsManager& args, SettingsAbortFn settings_abort_fn)
{
    try {
        if (!CheckDataDirOption(args)) {
            return ConfigError{ConfigStatus::FAILED, strprintf(_("Specified data directory \"%s\" does not exist."), args.GetArg("-datadir", ""))};
        }

        // Record original datadir and config paths before parsing the config
        // file. It is possible for the config file to contain a datadir= line
        // that changes the datadir path after it is parsed. This is useful for
        // CLI tools to let them use a different data storage location without
        // needing to pass it every time on the command line. (It is not
        // possible for the config file to cause another configuration to be
        // used, though. Specifying a conf= option in the config file causes a
        // parse error, and specifying a datadir= location containing another
        // bitcoin.conf file just ignores the other file.)
        const fs::path orig_datadir_path{args.GetDataDirBase()};
        const fs::path orig_config_path{AbsPathForConfigVal(args, args.GetPathArg("-conf", BITCOIN_CONF_FILENAME), /*net_specific=*/false)};

        std::string error;
        if (!args.ReadConfigFiles(error, true)) {
            return ConfigError{ConfigStatus::FAILED, strprintf(_("Error reading configuration file: %s"), error)};
        }

        // Check for chain settings (Params() calls are only valid after this clause)
        SelectParams(args.GetChainType());

        // Create datadir if it does not exist.
        const auto base_path{args.GetDataDirBase()};
        if (!fs::exists(base_path)) {
            // When creating a *new* datadir, also create a "wallets" subdirectory,
            // whether or not the wallet is enabled now, so if the wallet is enabled
            // in the future, it will use the "wallets" subdirectory for creating
            // and listing wallets, rather than the top-level directory where
            // wallets could be mixed up with other files. For backwards
            // compatibility, wallet code will use the "wallets" subdirectory only
            // if it already exists, but never create it itself. There is discussion
            // in https://github.com/bitcoin/bitcoin/issues/16220 about ways to
            // change wallet code so it would no longer be necessary to create
            // "wallets" subdirectories here.
            fs::create_directories(base_path / "wallets");
        }
        const auto net_path{args.GetDataDirNet()};
        if (!fs::exists(net_path)) {
            fs::create_directories(net_path / "wallets");
        }

        // Elektron Net: create a default bitcoin.conf on first launch
        const fs::path base_config_path = base_path / BITCOIN_CONF_FILENAME;
        if (!fs::exists(base_config_path)) {
            std::ofstream conf_file(fs::PathToString(base_config_path));
            if (conf_file.is_open()) {
                conf_file << "# ============================================\n"
                          << "# Elektron Net Configuration File\n"
                          << "# ============================================\n"
                          << "# This file is automatically generated on first launch.\n"
                          << "# Uncomment lines and modify values as needed.\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Network (P2P)\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Master seed node — used once for initial peer discovery (addrfetch).\n"
                          << "# seednode=seed.elektron-net.org:8333\n"
                          << "# seednode=188.20.182.78:8333\n"
                          << "\n"
                          << "# Manually add a permanent node (disables automatic discovery for this peer).\n"
                          << "# addnode=188.20.182.78:8333\n"
                          << "\n"
                          << "# Accept incoming P2P connections (required for a public node).\n"
                          << "listen=1\n"
                          << "\n"
                          << "# Maximum number of inbound/outbound connections (default: 125).\n"
                          << "# maxconnections=125\n"
                          << "\n"
                          << "# Bind to a specific address/interface (default: all interfaces).\n"
                          << "# bind=0.0.0.0\n"
                          << "\n"
                          << "# Connect only to the specified nodes (disables automatic peer discovery).\n"
                          << "# connect=seed.elektron-net.org:8333\n"
                          << "\n"
                          << "# Whitelist a peer to bypass rate limits and DoS scoring (use for trusted nodes).\n"
                          << "# whitelist=192.168.1.100\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# RPC Server\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Enable RPC server.\n"
                          << "server=1\n"
                          << "\n"
                          << "# RPC username and password for authentication.\n"
                          << "# WARNING: Use a strong, unique password in production.\n"
                          << "rpcuser=elek\n"
                          << "rpcpassword=pass\n"
                          << "\n"
                          << "# Bind RPC to localhost only (strongly recommended for security).\n"
                          << "rpcbind=127.0.0.1\n"
                          << "\n"
                          << "# Allow RPC connections only from localhost.\n"
                          << "rpcallowip=127.0.0.1\n"
                          << "\n"
                          << "# RPC port (default for mainnet: 9337).\n"
                          << "# rpcport=9337\n"
                          << "\n"
                          << "# Timeout for RPC requests in seconds (default: 30).\n"
                          << "# rpcservertimeout=30\n"
                          << "\n"
                          << "# Disable RPC cookie authentication (not recommended).\n"
                          << "# rpccookiefile=0\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Wallet\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Disable the wallet component entirely.\n"
                          << "# disablewallet=1\n"
                          << "\n"
                          << "# Automatically load all wallets in the <datadir>/wallets directory.\n"
                          << "# autoloadwallet=1\n"
                          << "\n"
                          << "# Load a specific wallet on startup (path relative to wallets dir).\n"
                          << "# wallet=mywallet\n"
                          << "\n"
                          << "# Transaction fee rate in Elek/kB (default: automatic).\n"
                          << "# paytxfee=0.0001\n"
                          << "\n"
                          << "# Allow spending unconfirmed change outputs.\n"
                          << "# spendzeroconfchange=1\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Mining / Staking\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Generate blocks (solo mining) when RPC getnewblock / generatetoaddress is called.\n"
                          << "# Only useful on regtest or if you have significant hashrate.\n"
                          << "# generatetoaddress=1\n"
                          << "\n"
                          << "# Coinbase reward destination address.\n"
                          << "# coinbasereceiver=be1q...\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Pruning (MANDATORY on Elektron Net)\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Elektron Net enforces mandatory 137-day pruning (197,280 blocks).\n"
                          << "# The values below only affect how much disk space the node tries to\n"
                          << "# reserve for the trailing window; they cannot disable pruning.\n"
                          << "\n"
                          << "# Target disk usage for block files in MiB (minimum: 550).\n"
                          << "# prune=550\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Performance / Memory\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Database cache size in MiB (default: 450; more = faster sync).\n"
                          << "# dbcache=2048\n"
                          << "\n"
                          << "# Number of script verification threads (-1 = auto).\n"
                          << "# par=4\n"
                          << "\n"
                          << "# Max memory for the mempool in MiB (default: 300).\n"
                          << "# maxmempool=300\n"
                          << "\n"
                          << "# Minimum fee rate to accept into mempool in Elek/kB.\n"
                          << "# minrelaytxfee=0.00001\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Indexes (optional)\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Build a full transaction index (requires more disk; incompatible with pruning).\n"
                          << "# NOT available on Elektron Net because pruning is mandatory.\n"
                          << "# txindex=1\n"
                          << "\n"
                          << "# Build a basic block filter index (BIP 157/158).\n"
                          << "# blockfilterindex=1\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Logging / Debug\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Log level: 0 = error, 1 = info, 2 = debug.\n"
                          << "# debug=1\n"
                          << "\n"
                          << "# Log specific categories (net, mempool, rpc, prune, validation, etc.).\n"
                          << "# debug=net\n"
                          << "# debug=mempool\n"
                          << "\n"
                          << "# Shrink debug.log file on startup.\n"
                          << "# shrinkdebugfile=1\n"
                          << "\n"
                          << "# Print to console instead of debug.log.\n"
                          << "# printtoconsole=1\n"
                          << "\n"
                          << "# --------------------------------------------\n"
                          << "# Advanced / Security\n"
                          << "# --------------------------------------------\n"
                          << "\n"
                          << "# Run as a daemon (background process) — only for elektrond.\n"
                          << "# daemon=1\n"
                          << "\n"
                          << "# Require a minimum number of confirmations before accepting a payment.\n"
                          << "# confirmations=6\n"
                          << "\n"
                          << "# Enable experimental ZeroMQ notifications (requires compiled support).\n"
                          << "# zmqpubhashtx=tcp://127.0.0.1:28332\n"
                          << "\n"
                          << "# Chain type: main, test, signet, regtest (default: main).\n"
                          << "# chain=main\n"
                          << "\n"
                          << "# Data directory path (default: OS-specific).\n"
                          << "# datadir=/var/lib/elektron-net\n"
                          << "\n"
                          << "# Configuration file path (default: <datadir>/bitcoin.conf).\n"
                          << "# conf=/etc/elektron-net/elektron.conf\n"
                          << "\n"
                          << "# Alert notify command — executed when a long fork is detected.\n"
                          << "# alertnotify=echo %%s | mail -s 'Elektron Alert' admin@example.com\n"
                          << "\n"
                          << "# Block notify command — executed when a new best block is accepted.\n"
                          << "# blocknotify=/usr/local/bin/notify.sh %%s\n"
                          << "\n"
                          << "# Wallet notify command — executed when a wallet transaction is received.\n"
                          << "# walletnotify=/usr/local/bin/wallet-notify.sh %%s\n";
            }
        }

        // Show an error or warn/log if there is a bitcoin.conf file in the
        // datadir that is being ignored.
        if (fs::exists(base_config_path)) {
            if (orig_config_path.empty()) {
                LogInfo(
                    "Data directory %s contains a %s file which is explicitly ignored using -noconf.",
                    fs::quoted(fs::PathToString(base_path)),
                    fs::quoted(BITCOIN_CONF_FILENAME));
            } else if (!fs::equivalent(orig_config_path, base_config_path)) {
                const std::string cli_config_path = args.GetArg("-conf", "");
                const std::string config_source = cli_config_path.empty()
                    ? strprintf("data directory %s", fs::quoted(fs::PathToString(orig_datadir_path)))
                    : strprintf("command line argument %s", fs::quoted("-conf=" + cli_config_path));
                std::string error = strprintf(
                    "Data directory %1$s contains a %2$s file which is ignored, because a different configuration file "
                    "%3$s from %4$s is being used instead. Possible ways to address this would be to:\n"
                    "- Delete or rename the %2$s file in data directory %1$s.\n"
                    "- Change datadir= or conf= options to specify one configuration file, not two, and use "
                    "includeconf= to include any other configuration files.",
                    fs::quoted(fs::PathToString(base_path)),
                    fs::quoted(BITCOIN_CONF_FILENAME),
                    fs::quoted(fs::PathToString(orig_config_path)),
                    config_source);
                if (args.GetBoolArg("-allowignoredconf", false)) {
                    LogWarning("%s", error);
                } else {
                    error += "\n- Set allowignoredconf=1 option to treat this condition as a warning, not an error.";
                    return ConfigError{ConfigStatus::FAILED, Untranslated(error)};
                }
            }
        }

        // Create settings.json if -nosettings was not specified.
        if (args.GetSettingsPath()) {
            std::vector<std::string> details;
            if (!args.ReadSettingsFile(&details)) {
                const bilingual_str& message = _("Settings file could not be read");
                if (!settings_abort_fn) {
                    return ConfigError{ConfigStatus::FAILED, message, details};
                } else if (settings_abort_fn(message, details)) {
                    return ConfigError{ConfigStatus::ABORTED, message, details};
                } else {
                    details.clear(); // User chose to ignore the error and proceed.
                }
            }
            if (!args.WriteSettingsFile(&details)) {
                const bilingual_str& message = _("Settings file could not be written");
                return ConfigError{ConfigStatus::FAILED_WRITE, message, details};
            }
        }
    } catch (const std::exception& e) {
        return ConfigError{ConfigStatus::FAILED, Untranslated(e.what())};
    }
    return {};
}
} // namespace common
